<?php
$homeUrl = $this->url('vitrine');
?>

<div class="row">
    <div class="col-md-12">

        <h2>Confirmation d'inscription</h2>

        <hr/>

        <p class="lead">
            Votre inscription à bien été prise en compte. Veuillez consultez votre
            boite email pour finaliser votre inscription.
        </p>
        <p>
            <a href="<?php echo $homeUrl; ?>" title="Aller &agrave; la page d'accueil">
                Retour &agrave; la page d'accueil
            </a>
        </p>

    </div>
</div>

