<?php
$homeUrl = $this->url('home');
?>

<div class="row">
    <div class="col-md-12">

        <h2>Confirmation d'activation</h2>

        <hr/>

        <p class="lead">
            Votre compte à bien été activé.
        </p>
        <p>
            <a href="<?php echo $homeUrl; ?>" title="Aller &agrave; la page d'accueil">
                Retour &agrave; la page d'accueil
            </a>
        </p>

    </div>
</div>

