<?php
$homeUrl = $this->url('home');
?>

<div class="row">
    <div class="col-md-12">

        <h2>Confirmation d'activation</h2>

        <hr/>
        <?php
        if($this->errors == null) {
        ?>
            <p class="lead">
                Votre compte à bien été activé.
            </p>
        <?php
        } else {
        ?>
            <p class="lead">
               Votre compte n'a pas été activé.
            </p>
        <?php
        }
        ?>
        <p>
            <a href="<?php echo $homeUrl; ?>" title="Aller &agrave; la page d'accueil">
                Retour &agrave; la page d'accueil
            </a>
        </p>
    </div>
</div>

