<?php
$form = $this->loginForm;
?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <form class="form-horizontal" enctype="multipart/form-data" method="post" role="form">

            <!-- Text input-->
            <?php
            if (isset($errors)) {
                echo $this->partial(
                    'gdpro-base/form-element/errors',
                    ['errors' => $errors]
                );
            }

            echo $this->partial(
                'gdpro-base/form-element/text',
                ['element' => $form->get('email')]
            );
            echo $this->partial(
                'gdpro-base/form-element/text',
                ['element' => $form->get('password')]
            );
            echo $this->partial(
                'gdpro-base/form-element/checkbox',
                ['element' => $form->get('stayConnected')]
            );

            echo $this->partial(
                'gdpro-base/form-element/submit',
                ['text' => 'Se connecter']
            );
            ?>
        </form>
    </div>
</div>